#!/bin/sh
echo ""BOT_TOKEN = "\"$BOT_TOKEN\"
"GDRIVE_FOLDER_ID = "\"$GDRIVE_FOLDER_ID\"
"TELEGRAPH_TOKEN = "\"$TELEGRAPH_TOKEN\"
"OWNER_ID = $OWNER_ID"
"DOWNLOAD_DIR = "\"$DOWNLOAD_DIR\"
"DOWNLOAD_STATUS_UPDATE_INTERVAL = $DOWNLOAD_STATUS_UPDATE_INTERVAL"
"AUTO_DELETE_MESSAGE_DURATION = $AUTO_DELETE_MESSAGE_DURATION"
"IS_TEAM_DRIVE = "\"$IS_TEAM_DRIVE\"
"INDEX_URL = "\"$INDEX_URL\"
"USER_SESSION_STRING = "\"$USER_SESSION_STRING\"
"TELEGRAM_API = $TELEGRAM_APP_ID"
"TELEGRAM_HASH = "\"$TELEGRAM_HASH\"
"USE_SERVICE_ACCOUNTS = "\"$USE_SERVICE_ACCOUNTS\"
"MEGA_API_KEY = "\"$MEGA_API_KEY\"
"MEGA_EMAIL_ID = "\"$MEGA_EMAIL_ID\"
"MEGA_PASSWORD = "\"$MEGA_PASSWORD\"
"STOP_DUPLICATE_MIRROR = "\"$STOP_DUPLICATE_MIRROR\"
"BUTTON_THREE_NAME = "\"$BUTTON_THREE_NAME\"
"BUTTON_THREE_URL = "\"$BUTTON_THREE_URL\"
"BUTTON_FOUR_NAME = "\"$BUTTON_FOUR_NAME\"
"BUTTON_FOUR_URL = "\"$BUTTON_FOUR_URL\"
"BUTTON_FIVE_NAME = "\"$BUTTON_FIVE_NAME\"
"BUTTON_FIVE_URL = "\"$BUTTON_FIVE_URL\" " >> config.env
echo -e $AUTH_CHATS >> authorized_chats.txt
if [ $USE_SERVICE_ACCOUNTS = "True" ]
then
	wget -q $SA_ZIP_URL -O accounts.zip
	unzip -qq accounts.zip -d ./
else
	wget -q $TOKEN_PICKLE_URL
fi	
./aria.sh; python3 -m bot